[20/04/2025 13:14:34] [INF] Aplicación iniciada
[20/04/2025 13:14:49] [INF] Accediendo a la lista de clientes
[20/04/2025 13:14:52] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:14:57] [INF] Accediendo a la vista de edición del cliente con CUIT: 20345054732
[20/04/2025 13:15:01] [INF] Cliente editado exitosamente: 20345054732
[20/04/2025 13:15:01] [INF] Accediendo a la lista de clientes
[20/04/2025 13:15:01] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:15:43] [INF] Accediendo a la vista de edición del cliente con CUIT: 20436601752
[20/04/2025 13:15:47] [WRN] Modelo inválido al editar cliente: 20436601752
[20/04/2025 13:16:04] [INF] Accediendo a la lista de clientes
[20/04/2025 13:16:04] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:16:06] [INF] Accediendo a la vista de creación de cliente
[20/04/2025 13:16:19] [WRN] Modelo inválido al crear cliente
[20/04/2025 13:16:39] [INF] Accediendo a la lista de clientes
[20/04/2025 13:16:39] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:19:01] [INF] Aplicación iniciada
[20/04/2025 13:20:12] [INF] Accediendo a la lista de clientes
[20/04/2025 13:20:13] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:20:18] [INF] Accediendo a la vista de creación de cliente
[20/04/2025 13:20:39] [INF] Aplicación iniciada
[20/04/2025 13:23:43] [INF] Aplicación iniciada
[20/04/2025 13:23:46] [INF] Accediendo a la lista de clientes
[20/04/2025 13:23:48] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:24:01] [INF] Accediendo a la lista de clientes
[20/04/2025 13:24:01] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:41:26] [INF] Aplicación iniciada
[20/04/2025 13:41:33] [INF] Accediendo a la lista de clientes
[20/04/2025 13:43:45] [INF] Aplicación iniciada
[20/04/2025 13:43:49] [INF] Accediendo a la lista de clientes
[20/04/2025 13:43:52] [INF] Lista de clientes cargada correctamente
[20/04/2025 13:52:16] [INF] Aplicación iniciada
[20/04/2025 13:52:19] [INF] Accediendo a la lista de clientes
[20/04/2025 13:53:18] [ERR] Error al obtener los clientes
System.Data.SqlClient.SqlException (0x80131904): Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): El sistema no puede encontrar el archivo especificado
   en System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   en System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.Open()
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   en System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass60_0.<UsingConnection>b__0()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass2_0.<Execute>b__0()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
   en System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript)
   en System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   en System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   en System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   en System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   en System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   en System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   en System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   en System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   en System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   en System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.GetAsyncEnumerator()
   en System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.ForEachAsync[T](IDbAsyncEnumerable`1 source, Action`1 action, CancellationToken cancellationToken)
   en System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.ToListAsync[T](IDbAsyncEnumerable`1 source, CancellationToken cancellationToken)
   en System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.ToListAsync[T](IDbAsyncEnumerable`1 source)
   en Ejercicio1_CRUD_Clientes.Services.ClienteService.<ObtenerTodosAsync>d__1.MoveNext() en C:\Users\micac\OneDrive\Escritorio\TUP\Ejercicio1-IntegraComex\Ejercicio1-CRUD_Clientes\Ejercicio1-CRUD_Clientes\Services\ClienteService.cs:línea 24
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Ejercicio1_CRUD_Clientes.Controllers.ClienteController.<Index>d__1.MoveNext() en C:\Users\micac\OneDrive\Escritorio\TUP\Ejercicio1-IntegraComex\Ejercicio1-CRUD_Clientes\Ejercicio1-CRUD_Clientes\Controllers\ClienteController.cs:línea 25
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
[20/04/2025 13:53:31] [INF] Accediendo a la vista de creación de cliente
[20/04/2025 13:53:35] [INF] Razon social obtenida para el CUIT: 27441519791
[20/04/2025 13:54:13] [ERR] Error al crear el cliente
System.Data.SqlClient.SqlException (0x80131904): Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): El sistema no puede encontrar el archivo especificado
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.Open()
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   en System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass60_0.<UsingConnection>b__0()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass2_0.<Execute>b__0()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
   en System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript)
   en System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   en System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   en System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   en System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   en System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   en System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   en System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   en System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   en System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   en System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Ejercicio1_CRUD_Clientes.Services.ClienteService.<AgregarAsync>d__3.MoveNext() en C:\Users\micac\OneDrive\Escritorio\TUP\Ejercicio1-IntegraComex\Ejercicio1-CRUD_Clientes\Ejercicio1-CRUD_Clientes\Services\ClienteService.cs:línea 49
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   en Ejercicio1_CRUD_Clientes.Controllers.ClienteController.<Create>d__3.MoveNext() en C:\Users\micac\OneDrive\Escritorio\TUP\Ejercicio1-IntegraComex\Ejercicio1-CRUD_Clientes\Ejercicio1-CRUD_Clientes\Controllers\ClienteController.cs:línea 51
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
[20/04/2025 13:58:57] [INF] Aplicación iniciada
[20/04/2025 13:58:58] [INF] Accediendo a la lista de clientes
[20/04/2025 13:59:05] [INF] Lista de clientes cargada correctamente
[20/04/2025 14:18:45] [INF] Aplicación iniciada
[20/04/2025 14:18:48] [INF] Accediendo a la lista de clientes
[20/04/2025 14:18:49] [INF] Lista de clientes cargada correctamente
